---
version: 2.1

jobs:
  build:
    docker:
      - image: 'circleci/node:latest'
    steps:
      - checkout
      - run: npm ci
      - run: npm run lint
      - run: npm test
      - run: npm run build
      - run: npm run semantic-release

workflows:
  build:
    jobs:
      - build:
          context: NPM release
